### ISSUE TITLE
Not Getting any results

### ISSUE THREAD

**Issue by anishvarghese** [jamotion/s3-exporter#1]
I have tried the the method and configured the config as in documentation ,but no results get

**Comment by anishvarghese** [comment]
Sorry its working after creating a folder inside the bucket not able to manage multiple buckets

**Comment by renzo1974** [comment]
Yes, with this version you only can check multiple folders in one bucket. There are some small changes needed to manage multiple buckets. 

We are currently working with one bucket for one customer instance (= VM). So we do not need this feature. If you would implement it I will be happy to merge your changes...

**Comment by renzo1974** [comment]
Issue closed due to lack of activity
