### ISSUE TITLE
Feature request: Support for environment variables in configuration

### ISSUE THREAD

**Issue by tobiasbp** [jamotion/s3-exporter#5]
I'd like to be able to use env variables for configuring the exporter. Especially the __secret_key__ and the __access_key__. I can make a pull request if you give me pointers as to how you would like me to implement it.

**Comment by renzo1974** [comment]
Hi
You can change the code to read ENV variables instead of config file here: 

https://github.com/jamotion/s3-exporter/blob/master/app/exporter.py#L46

If you would like to implement it, please allow both methods (config file and environment variables)
