### ISSUE TITLE
s3-exporter is not giving required metrics.

### ISSUE THREAD

**Issue by arvin-pjr** [jamotion/s3-exporter#6]
Hello Team,

I could use s3cmd tool alone but when running the exporter, it throws below error. Exporter is running but not showing any metrics on url.

`[v****@localhost s3-exporter]$ python3 app/exporter.py config/config.yml
app/exporter.py:149: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(config_file)
2020-09-07 07:54:14,967 - root - INFO - Starting server on port 9121

2020-09-07 07:54:42,003 - root - WARNING - Retrying failed request: /?delimiter=%2F&prefix=folder-1%2F (Remote end closed connection without response)
2020-09-07 07:54:42,003 - root - WARNING - Waiting 3 sec..`

**My config file.**

`access_key: "access-key"
secret_key: "secre-key"
host_base: "s3.amazonaws.com"
host_bucket: "%(bucket)s.s3.amazonaws.com"
use_https: True
signature_v2: True
bucket: "bucketname"
pattern: "*."
folders:
  - "folder-1"
  - "folder-2"`

**Comment by renzo1974** [comment]
I have developed this Exporter for Exoscale.com only. If you need it for AWS, feel free to optimize the code and create a pull request.
